services:
  db:
    container_name: postgres
    image: postgres
    hostname: localhost
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
